name: Build Android APK (Signed)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Build Release APK (Unsigned)
        run: ./gradlew assembleRelease
      - name: Show build outputs
        run: ls -R app/build/outputs
      - name: Sign Release APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: app/build/outputs/apk/release/*.apk
