name: Build Android Debug APK

on:
  workflow_dispatch:
  push:
    paths:
      - "**"
      - ".github/workflows/android.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Android SDK manually
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk
          sudo chown $USER:$USER /usr/local/lib/android/sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d /usr/local/lib/android/sdk/
          mv /usr/local/lib/android/sdk/cmdline-tools /usr/local/lib/android/sdk/cmdline-tools-temp
          mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest
          mv /usr/local/lib/android/sdk/cmdline-tools-temp/* /usr/local/lib/android/sdk/cmdline-tools/latest/
          yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle (Debug APK)
        run: ./gradlew ":androidApp:assembleDebug" --stacktrace --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: androidApp/build/outputs/apk/debug/*.apk
